

export const OFFICER_ROLES = [
  "Senior Team Leader",
  "Team Leader",
  "Assistant Team Leader",
  "Scribe",
];

export const COLOR_OPTIONS = [
  { value: "c-slate", label: "Slate (grey-blue)" },
  { value: "c-crimson", label: "Crimson (red)" },
  { value: "c-purple", label: "Purple" },
  { value: "c-teal", label: "Teal" },
  { value: "c-ember", label: "Ember (orange)" },
  { value: "c-forest", label: "Forest (green)" },
  { value: "c-olive", label: "Olive" },
  { value: "c-navy", label: "Navy (blue)" },
  { value: "c-gold", label: "Gold" },
  { value: "c-magenta", label: "Magenta (pink)" },
  { value: "c-indigo", label: "Indigo" },
  { value: "c-deep-teal", label: "Deep Teal" },
];
export const MONTHS = [
  "jan",
  "feb",
  "mar",
  "apr",
  "may",
  "jun",
  "jul",
  "aug",
  "sep",
  "oct",
  "nov",
  "dec",
];

const DEFAULT_THINGS_TO_BRING = [
  "Day pack / Overnight pack",
  "Water, 2–3 litres per day",
  "Snacks / Trail food",
  "Packed meals",
  "Mess kit",
  "Sunscreen / Umbrella",
  "Jacket (preferably rainproof)",
  "Rain gear",
  "Emergency blanket",
  "Individual first aid kit",
  "Personal toiletries",
  "Head lamp",
  "Camera / Mobile phone",
  "Plastic bag / Trash bag",
];

export const EMPTY_FORM = {
  title: "",
  dateLabel: "",
  month: "jul",
  startDate: "",
  endDate: "",
  location: "",
  type: "minor",
  color: "c-slate",
  status: "draft",
  cancellationStatus: "",
  cancellationReason: "",
  maxParticipants: 30,
  isWide: false,
  itineraryReady: false,
  description: "",
  // Mountain profile
  elevation: "",
  difficulty: "",
  trailClass: "",
  jumpOff: "",
  jumpOffElevation: "",
  elevationGain: "",
  distanceToSummit: "",
  roundTripDistance: "",
  recommendedDays: "",
  features: "",
  googleMapsUrl: "",
  allTrailsUrl: "",
  trailImages: [],
  waterSourceNote: "",
  weatherNote: "",
  thingsToBring: [...DEFAULT_THINGS_TO_BRING],
  fees: [
    { label: "Registration Fee", amount: "TBA", note: "", optional: false },
    { label: "Guide Fee", amount: "TBA", note: "", optional: false },
    { label: "Environmental Fee", amount: "TBA", note: "", optional: false },
    {
      label: "Guest Fee",
      amount: "450",
      note: "Required for non-members / guests. Not charged to MMS members.",
      optional: true,
      isGuestFee: true,
    },
    {
      label: "Transportation Fee",
      amount: "TBA",
      note: "Only if availing organized transport",
      optional: true,
    },
    {
      label: "Food & Meals",
      amount: "TBA",
      note: "Only if availing organized meals",
      optional: true,
    },
  ],
  officers: [],
  officerEmails: [],
  itinerary: [],
  announcements: [],
  preClimbMeetings: [],
  resources: [],
  trailMaps: [],
  gcashName: "",
  gcashNumber: "",
  gcashQrUrl: "",
  requiresRegistrationForm: false,
  registrationFormUrl: "",
  registrationFormFileName: "",
  requiresMedicalCert: false,
  medicalCertSampleUrl: "",
  medicalCertSampleFileName: "",
  requiresPermit: false,
  permitSampleUrl: "",
  permitSampleFileName: "",
  requiresWaiverDoc: false,
  waiverDocSampleUrl: "",
  waiverDocSampleFileName: "",
};
